-- Basic
require("core.plugins")
require("core.config")
require("core.autocommands")
require("core.mappings")
require("core.theme")

-- Plugins
require("plugins.cmp")
require("plugins.neotree")
require("plugins.treesitter")
require("plugins.lsp")
require("plugins.mason")
require("plugins.telescope")
require("plugins.conform")
require("plugins.comment")
require("plugins.lualine")
require("plugins.autopairs")
require("plugins.autotag")
require("plugins.bufferline")
require("plugins.dashboard")
require("plugins.snippy")
require("plugins.whichkey")
require("plugins.hop")
